name: ct_clean
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Language
  flutter_localizations:
    sdk: flutter
  intl: null
  # Basic dependency
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  # image
  image_cropper:
  image_picker:
  flutter_svg: ^2.0.9
  lottie: ^2.6.0
  cached_network_image: ^3.3.1
  # pop
  fluttertoast: ^8.2.4
  # Map
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_maps_flutter: ^2.5.2
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.2.4
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.3.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  permission_handler: ^11.3.0
  # make custom loading
  shimmer: ^3.0.0
  searchfield: ^0.9.0
  restart_app: ^1.2.1
  firebase_messaging: ^14.8.0
  firebase_core: ^2.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # To Change name and packageID
  rename: ^3.0.2
  flutter_launcher_icons: "^0.13.1"
  # Generate Images
  build_runner: ^2.1.5
  flutter_gen_runner: ^5.1.0+1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash12.png"
  min_sdk_android: 21

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/logo.png"
#  min_sdk_android: 21



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/svgs/
     - assets/demo/
     - assets/lottie/
     - assets/fonts/
     - lang/ar.json
     - lang/en.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Almarai
       fonts:
         - asset: assets/fonts/Almarai-Regular.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
